_extends: org-settings
repository:
  name: [name]
  description: [description]
  topics: [topics]
  homepage: https://github.com/telus/[name]
  private: [private]

branches:
  - name: master
    protection:
      enforce_admins: true
      # required_pull_request_reviews:
      #   dismissal_restrictions:
      #     teams:
      #       - [team]
      # restrictions:
      #   teams:
      #     - [team]
      # required_status_checks:
      #  strict: true
      #  contexts:
      #    - "default"

teams:
  - name: [team]
    permission: admin
