_extends: org-settings
repository:
  name: create-library
  description: TELUS NPM Library Initializer
  topics: telus, initializer, npm, init, create, library
  homepage: https://github.com/telus/create-library
  private: false

branches:
  - name: master
    protection:
      enforce_admins: true
      # required_pull_request_reviews:
      #   dismissal_restrictions:
      #     teams:
      #       - architecture-support
      # restrictions:
      #   teams:
      #     - architecture-support
      # required_status_checks:
      #  strict: true
      #  contexts:
      #    - "default"

teams:
  - name: architecture-support
    permission: admin
  - name: telus
    permission: write
