version: 4.0

id: create-library
uid: 152944324

about:
  title: create-library
  description: An opinionated NPM Package initializer

contacts:
  - type: Project Owner
    name: Shimona Jain
    email: shimona.jain@telus.com
  - type: Team
    name: ptt-ti
    members_uri: https://github.com/orgs/telus/teams/ptt-ti/members
    repositories_uri: https://github.com/orgs/telus/teams/ptt-ti/repositories

references:
  - title: git
    description: Source Code
    uri: https://github.com/telus/create-library.git

environments:
  - type: git
    title: NPM Package
    uri: https://www.npmjs.com/package/@telus/create-library
