version: 2.0

id: create-library

about:
  title: create-library
  description: An opinionated NPM Package initializer

contacts:
  - type: Project Manager
    name: Natasha Lander
    email: natasha.lander@telus.com
    github: NatashaLander
  - type: developer
    name: Mauricio Mercado
    email: mauricio.mercado@telus.com
    github: maumercado
  - type: developer
    name: Matthew Cantelon
    email: matthew.cantelon@telus.com
    github: mattcan
  - type: Product Owner
    name: Katarina Sokach
    email: katarina.sokach@telus.com
  - type: Tech Lead
    name: Stephen Marie-Rhodes
    email: stephen.marie-rhodes@telus.com

references:
  - title: NPM Package
    uri: https://www.npmjs.com/package/@telus/create-library

environments:
  - type: git
    title: Source Code
    uri: https://github.com/telus/create-library
