version: 2.0

id: create-library

about:
  title: create-library
  description: An opinionated NPM Package initializer

contacts:
  - type: Project Manager
    name: Natasha Lander
    email: natasha.lander@telus.com
    github: NatashaLander
  - type: developer
    name: Mauricio Mercado
    email: mauricio.mercado@telus.com
    github: maumercado
  - type: developer
    name: Samantha Vale
    email: samantha.bezerra_vale@telus.com
    github: karlasamantha
  - type: developer
    name: Ruxandra Fediuc
    email: ruxandra.fediuc@telus.com
    github: ruxandrafed
  - type: developer
    name: Matt Seburn
    email: matt.seburn@telus.com
    github: mattseburn
  - type: developer
    name: Bill Li
    email: bill.li@telus.com
    github: billxinli
  - type: Product Owner
    name: Daniel Tyrala
    email: daniel.tyrala@telus.com

references:
  - title: NPM Package
    uri: https://www.npmjs.com/package/@telus/create-library

environments:
  - type: Git
    title: Source Code
    uri: https://github.com/telus/create-library
