version: 2.0

id: create-library

about:
  title: create-library
  description: An opinionated NPM Package initializer

  contacts:
    - type: Product Owner
      name: Stephen Marie-Rhodes
      email: Stephen.Marie-Rhodes@telus.com
      github: stepmr
    - type: Tech Lead
      name: Mauricio Mercado
      email: mauricio.mercado@telus.com
      github: maumercado
    - type: Architect
      name: Matthew Cantelon
      email: matthew.cantelon@telus.com
      github: mattcan

references:
  - title: NPM Package
    uri: https://www.npmjs.com/package/@telus/create-library

environments:
  - type: git
    title: Source Code
    uri: https://github.com/telus/create-library
