apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: create-library
  description: An opinionated NPM Package initializer
  tags:
    - node
    - github-actions
    - workflows
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/name=create-library
    backstage.io/techdocs-ref: dir:docs
    github.com/project-slug: telus/create-library
    telus.com/vp: harry.mcintosh@telus.com
    telus.com/director: steve.tannock@telus.com
    telus.com/manager: stephen.marie-rhodes@telus.com
    telus.com/maintainer: valentin.prugnaud@telus.com
  links:
    - url: https://github.com/telus/create-library
      title: Website
      icon: web
spec:
  type: service
  lifecycle: experimental
  owner: telus
  system: digital
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: create-library
  description: An opinionated NPM Package initializer
  tags:
    - node
  annotations:
    github.com/project-slug: telus/create-library
  links:
    - url: https://github.com/telus/create-library
      title: API Spec
      icon: code
    - url: https://github.com/telus/create-library
      title: Website
      icon: web
spec:
  type: openapi
  lifecycle: experimental
  owner: digital
  definition:
    $text: https://github.com/telus/create-library
