apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  title: npm Library Initializer
  name: npm-library-initializer
  namespace: default
  snackDescription: An npm Library Initializer that makes creating and publishing an npm package faster and easier
  description: This npm Library Initializer is a command-line interface tool that greatly simplifies the process of creating and publishing a new npm package for use within TELUS.
  url: https://github.com/telus/create-library
  audiences: []
  category: 5H8LFm5kPoZtIHqz0z5eTf
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/telus/create-library
spec:
  type: documentation
  lifecycle: experimental
  owner: 7zOeDTI9qea36oEiDbXcMx
