name: Publish TechDocs Site
'on':
  push:
    branches:
      - main
    paths:
      - docs/**
      - .github/workflows/main.yaml
      - '**.md'
jobs:
  publish-techdocs-site:
    runs-on: ubuntu-latest
    env:
      ENTITY_NAME: npm-library-initializer
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/setup-python@v2
        with:
          python-version: 3.11.3

      - uses: google-github-actions/setup-gcloud@v1
        with:
          version: 290.0.1
          project_id: ${{ secrets.SIMPLIFY_HUB_GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.SIMPLIFY_HUB_GCP_SA_KEY }}
          export_default_credentials: true

      - name: Generate images for PlantUML diagrams
        uses: cloudbees/plantuml-github-action@master

      - name: Get TechDocs guide github actions
        uses: actions/checkout@v3
        with:
          repository: telus/techdocs-common-files
          ref: main
          token: ${{ secrets.SIMPLIFY_HUB_GITHUB_TOKEN }}
          path: common-files

      - name: TechDocs guide building
        uses: ./common-files/actions/guides
        with:
          github-token: ${{ secrets.SIMPLIFY_HUB_GITHUB_TOKEN }}
