name: 'Publish package on merge to master'

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish package
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install deps
        run: npm ci

      - name: Publish package to npmjs.org
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Setup Github credentials for Github Packages access
        run: |
          echo @telus:https://npm.pkg.github.com/ > .npmrc
          echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> .npmrc

      - name: Publish package to Github Packages
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
